## 인덱싱

In [4]:
import numpy as np
A = np.arange(0,15,2)
print(A)

[ 0  2  4  6  8 10 12 14]


In [5]:
print(A.shape)
for i in range(A.size) :
    print(A[i], end=" ")

(8,)
0 2 4 6 8 10 12 14

In [6]:
print(A.shape)
for i in range(A.size) :
    print("A[{}] : {}".format(i,A[i]))

(8,)
A[0] : 0
A[1] : 2
A[2] : 4
A[3] : 6
A[4] : 8
A[5] : 10
A[6] : 12
A[7] : 14


In [8]:
for i in range(A.size) :
    n = -(i+1) 
    print("A[{}] : {}".format(n,A[n]))

A[-1] : 14
A[-2] : 12
A[-3] : 10
A[-4] : 8
A[-5] : 6
A[-6] : 4
A[-7] : 2
A[-8] : 0


In [16]:
import numpy as np
A = np.arange(12).reshape(3,4)
print(A)
print("A.ndim :",A.ndim)
print(A.shape,A.shape[0],A.shape[1])
for i in range(A.shape[0]) :
    for j in range(A.shape[1]) :
        print("A[{0}][{1}] : {2:2d}".format(i,j,A[i][j]), end=" ")
    print()

for i in range(A.shape[0]) :
    print("A[{}]:{}".format(i,A[i]))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
A.ndim : 2
(3, 4) 3 4
A[0][0] :  0 A[0][1] :  1 A[0][2] :  2 A[0][3] :  3 
A[1][0] :  4 A[1][1] :  5 A[1][2] :  6 A[1][3] :  7 
A[2][0] :  8 A[2][1] :  9 A[2][2] : 10 A[2][3] : 11 
A[0]:[0 1 2 3]
A[1]:[4 5 6 7]
A[2]:[ 8  9 10 11]


## T

In [20]:
import numpy as np

A = np.arange(9).reshape(3,3)
print(A)

for row in A : # A => [[0,1,2],[3,4,5],[6,7,8]]
    print(row)

print()

print(A.T) # 전치행렬 : 행과 열의 값을 바꿈

for column in A.T :
    print(column)


[[0 1 2]
 [3 4 5]
 [6 7 8]]
[0 1 2]
[3 4 5]
[6 7 8]

[[0 3 6]
 [1 4 7]
 [2 5 8]]
[0 3 6]
[1 4 7]
[2 5 8]


## flat

In [24]:
import numpy as np
A = np.arange(9).reshape(3,3)
print(A)
print()
for a in A.flat :
    print(a,end=" ")

[[0 1 2]
 [3 4 5]
 [6 7 8]]

0 1 2 3 4 5 6 7 8

In [62]:
import numpy as np
A = np.arange(0,20,2) # 1차원 배열 생성
print(A)

[ 0  2  4  6  8 10 12 14 16 18]


In [38]:
print(A[0:3])

[0 2 4]


In [39]:
print(A[0:3])
print(A[:3]) # 0에서 시작하면 생략가능

[0 2 4]
[0 2 4]


In [40]:
print(A[7:10])
print(A[7:]) # 끝 인덱스 생략가능

[14 16 18]
[14 16 18]


In [50]:
print(A[:]) # 전체원소
print(A[::2]) # 첫번째 원소부터 2씩 건너뜀

[ 0  2  4  6  8 10 12 14 16 18]
[ 0  4  8 12 16]


In [57]:
print(A[-1000:-2]) # 마지막 2개 원소 제외
print(A[-10:-2]) # 마지막 2개 원소 제외
print(A[:-2]) # 마지막 2개 원소 제외

[ 0  2  4  6  8 10 12 14]
[ 0  2  4  6  8 10 12 14]
[ 0  2  4  6  8 10 12 14]


In [58]:
print(A[-2:1000]) # 마지막 원소 2개만 취함
print(A[-2:]) # 마지막 원소 2개만 취함

[16 18]
[16 18]


In [59]:
print(A[0:3].shape)
print(A[0:3].ndim)

(3,)
1


In [63]:
print(A)
A[0:3] = 100
print(A)

[ 0  2  4  6  8 10 12 14 16 18]
[100 100 100   6   8  10  12  14  16  18]


In [66]:
import numpy as np
A = np.arange(1,13).reshape(3,4)
print(A)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


## 각원소에 접근
 - A[row][col] or A[row,col]

In [71]:
for i in range(A.shape[0]) :
    for j in range(A.shape[1]) :
        print("A[{}][{}] : {:2d} or A[{},{}] : {:2d}".format(i,j,A[i][j],i,j,A[i,j]))

A[0][0] :  1 or A[0,0] :  1
A[0][1] :  2 or A[0,1] :  2
A[0][2] :  3 or A[0,2] :  3
A[0][3] :  4 or A[0,3] :  4
A[1][0] :  5 or A[1,0] :  5
A[1][1] :  6 or A[1,1] :  6
A[1][2] :  7 or A[1,2] :  7
A[1][3] :  8 or A[1,3] :  8
A[2][0] :  9 or A[2,0] :  9
A[2][1] : 10 or A[2,1] : 10
A[2][2] : 11 or A[2,2] : 11
A[2][3] : 12 or A[2,3] : 12


## 행의 슬라이싱
  - A[i] or A[i,:] 

In [75]:
for i in range(A.shape[0]) :
    print("A[{0}] : {1} or A[{2},:] : {3}".format(i,A[i],i,A[i,:]))

A[0] : [1 2 3 4] or A[0,:] : [1 2 3 4]
A[1] : [5 6 7 8] or A[1,:] : [5 6 7 8]
A[2] : [ 9 10 11 12] or A[2,:] : [ 9 10 11 12]


In [77]:
print(A)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [79]:
print(A[:2,:2])

[[1 2]
 [5 6]]


In [81]:
A[:2,:2]=0
print(A)

[[ 0  0  3  4]
 [ 0  0  7  8]
 [ 9 10 11 12]]


In [88]:
import numpy as np
A = np.arange(1,13).reshape(3,4)
print(A)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [89]:
print(A[0]) # 행 슬라이싱
print(A[:,1]) # 열 슬라이싱
print(A[...,1]) # 열 슬라이싱

[1 2 3 4]
[ 2  6 10]
[ 2  6 10]


In [94]:
import numpy as np
A = np.array([2,4,6,8]).reshape(2,2)
B = np.array([2,2,2,2]).reshape(2,2)
print(A)
print(B)

[[2 4]
 [6 8]]
[[2 2]
 [2 2]]


In [95]:
print(A+B)
print(A-B)
print(A*B)
print(A/B)

[[ 4  6]
 [ 8 10]]
[[0 2]
 [4 6]]
[[ 4  8]
 [12 16]]
[[1. 2.]
 [3. 4.]]


In [96]:
print(A@B) # 행렬의 곱셈

[[12 12]
 [28 28]]


In [97]:
print(np.dot(A,B)) # 행렬의 곱셈
print(A.dot(B)) # 행렬의 곱셈

[[12 12]
 [28 28]]
[[12 12]
 [28 28]]


## 다른 크기의 배열간의 산술연산(브로드캐스팅)
A.shape = (2,3,4,5)  
B.shape = (5,) => B의 차원의 개수가 같아지도록 B shape 왼쪽에 1추가  
B.shape = (1,1,1,5)  
- 두 배열을 비교
- 대응하는 차원이 같거나 한쪽이 1인 경우에만 브로드캐스팅 가능

A.shape : (2,1,3,1)  
B.shape : (6,1,3)  
B의 차원의 개수가 같아지도록 B shape 왼쪽에 1추가  
=> B.shape : (1,6,1,3)  
=> 브로드캐스팅 가능

A.shape : (2,3,4)  
B.shape : (3,1)  
B의 차원의 개수가 같아지도록 B shape 왼쪽에 1추가  
=> B.shape : (1,3,1)  
=> 브로드캐스팅 가능  


A.shape : (3,)  
B.shape : (4,)  
=> 브로드캐스팅 불가능

A.shape : (3,3,5)  
B.shape : (3,1,5)  
=> 브로드캐스팅 가능

In [111]:
import numpy as np
A=np.arange(10,130,10).reshape(3,4)
print(A)
print(A.shape)
B= np.arange(1,5)
print(B)
print(B.shape)

print(A@B)

[[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]]
(3, 4)
[1 2 3 4]
(4,)
[ 300  700 1100]


In [102]:
A+B

array([[ 11,  22,  33,  44],
       [ 51,  62,  73,  84],
       [ 91, 102, 113, 124]])

A.shape : (3,4)  
B.shape : (3,) => (1,3)  
=> 브로드캐스팅 불가능

In [110]:
import numpy as np
A = np.arange(10,130,10).reshape(3,4)
print(A)
print(A.shape)
B = np.arange(1,4)
print(B)
print(B.shape)
A+B

[[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]]
(3, 4)
[1 2 3]
(3,)


ValueError: operands could not be broadcast together with shapes (3,4) (3,) 

In [119]:
import numpy as np
A = np.arange(10,130,10).reshape(3,4)
print(A)
print(A.shape)
B = 5
# print(B.shape)
print(A+B)

[[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]]
(3, 4)
[[ 15  25  35  45]
 [ 55  65  75  85]
 [ 95 105 115 125]]


## vectorize

In [120]:
import numpy as np
matrix = np.arange(1,10).reshape(3,3)
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [121]:
add_100 = lambda i : i+100

In [122]:
vectorized_add_100 = np.vectorize(add_100)
vectorized_add_100(matrix)

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

In [127]:
find_odd = lambda i : i*(i%2)
find_enven = lambda i : i if i%2 == 0 else 0
vectorized_find_odd = np.vectorize(find_odd)
vectorized_find_enven = np.vectorize(find_enven)
print(vectorized_find_odd(matrix))
print(vectorized_find_enven(matrix))

[[1 0 3]
 [0 5 0]
 [7 0 9]]
[[0 2 0]
 [4 0 6]
 [0 8 0]]


In [135]:
import numpy as np
matrix = np.arange(1,10).reshape(3,3)
print(matrix)

print(np.max(matrix))
print(np.min(matrix))
print(np.max(matrix, axis=1)) # 각 행에서 최대값 찾음
print(np.min(matrix, axis=0)) # 각 열에서 최소값 찾음

[[1 2 3]
 [4 5 6]
 [7 8 9]]
9
1
[3 6 9]
[1 2 3]


In [132]:
vector_column = np.max(matrix, axis=1, keepdims=True)
print(vector_column)
print(vector_column.shape)

[[3]
 [6]
 [9]]
(3, 1)


In [133]:
print(matrix.shape)
print(matrix - vector_column)

(3, 3)
[[-2 -1  0]
 [-2 -1  0]
 [-2 -1  0]]


## 평균 분사 표준편차

In [141]:
import numpy as np
matrix = np.arange(1,10).reshape(3,3)
print(matrix)

print("평균 :",np.mean(matrix))
print("분산 :",np.var(matrix))
print("표준편차 :",np.std(matrix))


[[1 2 3]
 [4 5 6]
 [7 8 9]]
평균 : 5.0
분산 : 6.666666666666667
표준편차 : 2.581988897471611


In [139]:
print("평균 :",np.mean(matrix))
print("평균 :",np.mean(matrix, axis=0)) # 각열의 평균

평균 : 5.0
평균 : [4. 5. 6.]


In [142]:
print(np.std(matrix))
print(np.std(matrix, ddof=1))

2.581988897471611
2.7386127875258306


## 행렬의 전치(전치행렬, Transpose)

In [146]:
import numpy as np
matrix = np.arange(1,10).reshape(3,3)
print(matrix)
print()
print(matrix.T)
print(matrix.transpose())

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1 4 7]
 [2 5 8]
 [3 6 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [145]:
np.array([[1,2,3,4,5,6,7]]).T

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7]])

In [148]:
matrix = np.array([[1,1,1],[1,1,10],[1,1,15]])
print(matrix)
np.linalg.matrix_rank(matrix)

[[ 1  1  1]
 [ 1  1 10]
 [ 1  1 15]]


2

## inverse matrix

In [150]:
matrix = np.array([[1,4],[2,5]])
print(matrix)

[[1 4]
 [2 5]]


In [152]:
# 역행렬
inv_matrix = np.linalg.inv(matrix)
print(inv_matrix)

[[-1.66666667  1.33333333]
 [ 0.66666667 -0.33333333]]


In [153]:
matrix @ inv_matrix

array([[1., 0.],
       [0., 1.]])

In [156]:
matrix = np.arange(1,7).reshape(2,3)
print(matrix)

[[1 2 3]
 [4 5 6]]


In [157]:
inv_matrix = np.linalg.pinv(matrix)
print(inv_matrix)

[[-0.94444444  0.44444444]
 [-0.11111111  0.11111111]
 [ 0.72222222 -0.22222222]]


In [160]:
print(np.round(matrix @ inv_matrix,0))

[[1. 0.]
 [0. 1.]]


In [162]:
import random
a = np.arange(5)
print(a)
np.random.shuffle(a)
print(a)

[0 1 2 3 4]
[1 0 3 4 2]


In [163]:
import random
a = np.arange(5)
print(a)
b = np.random.permutation(a)
print(b)

[0 1 2 3 4]
[2 1 3 0 4]


In [164]:
print(np.random.permutation(5))

[4 2 0 1 3]
